CREATE TABLE ${flyway:defaultSchema}.wallets
(
    "id"                           bigint                   NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 10000 MINVALUE 10000 MAXVALUE 9223372036854775807 CACHE 1 ),
    "wallet_generation_request_id" bigint                   NOT NULL,
    "blockchain_id"                text                     NOT NULL,
    "protocol_code"                text                     NOT NULL,
    "network_type"                 text                     NOT NULL,
    "address"                      text                     NOT NULL,
    "public_key"                   text                     NOT NULL,
    "private_key"                  text                     NOT NULL,
    "created_at"                   timestamp with time zone NOT NULL,
    CONSTRAINT "pk_wallets" PRIMARY KEY ("id")
);

ALTER TABLE ${flyway:defaultSchema}.wallets
    OWNER to ${flyway:user};

CREATE INDEX "ix_wallets_address"
    ON ${flyway:defaultSchema}.wallets (address);

CREATE UNIQUE INDEX "ix_wallets_wallet_generation_request_id"
    ON ${flyway:defaultSchema}.wallets (wallet_generation_request_id);