// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface DecryptResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.DecryptResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Plain = 3;</code>
   *
   * @return The plain.
   */
  com.google.protobuf.ByteString getPlain();
}
