// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface DecryptSingleRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.DecryptSingleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Key = 1;</code>
   *
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>.grep11.Mechanism Mech = 2;</code>
   *
   * @return Whether the mech field is set.
   */
  boolean hasMech();
  /**
   * <code>.grep11.Mechanism Mech = 2;</code>
   *
   * @return The mech.
   */
  com.ibm.crypto.grep11.grpc.Mechanism getMech();
  /** <code>.grep11.Mechanism Mech = 2;</code> */
  com.ibm.crypto.grep11.grpc.MechanismOrBuilder getMechOrBuilder();

  /**
   * <code>bytes Ciphered = 3;</code>
   *
   * @return The ciphered.
   */
  com.google.protobuf.ByteString getCiphered();
}
