// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface DeriveKeyResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.DeriveKeyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes NewKey = 6;</code>
   *
   * @return The newKey.
   */
  com.google.protobuf.ByteString getNewKey();

  /**
   * <code>bytes CheckSum = 7;</code>
   *
   * @return The checkSum.
   */
  com.google.protobuf.ByteString getCheckSum();
}
