// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface DigestInitResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.DigestInitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes State = 1;</code>
   *
   * @return The state.
   */
  com.google.protobuf.ByteString getState();
}
