// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface DigestSingleResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.DigestSingleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Digest = 3;</code>
   *
   * @return The digest.
   */
  com.google.protobuf.ByteString getDigest();
}
