// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface EncryptSingleResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.EncryptSingleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Ciphered = 4;</code>
   *
   * @return The ciphered.
   */
  com.google.protobuf.ByteString getCiphered();
}
