// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface EncryptRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.EncryptRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes State = 1;</code>
   *
   * @return The state.
   */
  com.google.protobuf.ByteString getState();

  /**
   * <code>bytes Plain = 2;</code>
   *
   * @return The plain.
   */
  com.google.protobuf.ByteString getPlain();
}
