// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface GenerateRandomRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.GenerateRandomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 Len = 1;</code>
   *
   * @return The len.
   */
  long getLen();
}
