// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface GenerateKeyPairResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.GenerateKeyPairResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes PrivKey = 5;</code>
   *
   * @return The privKey.
   */
  com.google.protobuf.ByteString getPrivKey();

  /**
   * <code>bytes PubKey = 6;</code>
   *
   * @return The pubKey.
   */
  com.google.protobuf.ByteString getPubKey();
}
