// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

/** Protobuf type {@code grep11.GenerateKeyPairRequest} */
public final class GenerateKeyPairRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:grep11.GenerateKeyPairRequest)
    GenerateKeyPairRequestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use GenerateKeyPairRequest.newBuilder() to construct.
  private GenerateKeyPairRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private GenerateKeyPairRequest() {
    privKeyId_ = "";
    pubKeyId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new GenerateKeyPairRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private GenerateKeyPairRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              com.ibm.crypto.grep11.grpc.Mechanism.Builder subBuilder = null;
              if (mech_ != null) {
                subBuilder = mech_.toBuilder();
              }
              mech_ =
                  input.readMessage(
                      com.ibm.crypto.grep11.grpc.Mechanism.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mech_);
                mech_ = subBuilder.buildPartial();
              }

              break;
            }
          case 18:
            {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                pubKeyTemplate_ =
                    com.google.protobuf.MapField.newMapField(
                        PubKeyTemplateDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Long, com.google.protobuf.ByteString>
                  pubKeyTemplate__ =
                      input.readMessage(
                          PubKeyTemplateDefaultEntryHolder.defaultEntry.getParserForType(),
                          extensionRegistry);
              pubKeyTemplate_
                  .getMutableMap()
                  .put(pubKeyTemplate__.getKey(), pubKeyTemplate__.getValue());
              break;
            }
          case 26:
            {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                privKeyTemplate_ =
                    com.google.protobuf.MapField.newMapField(
                        PrivKeyTemplateDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Long, com.google.protobuf.ByteString>
                  privKeyTemplate__ =
                      input.readMessage(
                          PrivKeyTemplateDefaultEntryHolder.defaultEntry.getParserForType(),
                          extensionRegistry);
              privKeyTemplate_
                  .getMutableMap()
                  .put(privKeyTemplate__.getKey(), privKeyTemplate__.getValue());
              break;
            }
          case 42:
            {
              java.lang.String s = input.readStringRequireUtf8();

              privKeyId_ = s;
              break;
            }
          case 50:
            {
              java.lang.String s = input.readStringRequireUtf8();

              pubKeyId_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.ibm.crypto.grep11.grpc.Hsm.internal_static_grep11_GenerateKeyPairRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(int number) {
    switch (number) {
      case 2:
        return internalGetPubKeyTemplate();
      case 3:
        return internalGetPrivKeyTemplate();
      default:
        throw new RuntimeException("Invalid map field number: " + number);
    }
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ibm.crypto.grep11.grpc.Hsm
        .internal_static_grep11_GenerateKeyPairRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest.class,
            com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest.Builder.class);
  }

  public static final int MECH_FIELD_NUMBER = 1;
  private com.ibm.crypto.grep11.grpc.Mechanism mech_;
  /**
   * <code>.grep11.Mechanism Mech = 1;</code>
   *
   * @return Whether the mech field is set.
   */
  @java.lang.Override
  public boolean hasMech() {
    return mech_ != null;
  }
  /**
   * <code>.grep11.Mechanism Mech = 1;</code>
   *
   * @return The mech.
   */
  @java.lang.Override
  public com.ibm.crypto.grep11.grpc.Mechanism getMech() {
    return mech_ == null ? com.ibm.crypto.grep11.grpc.Mechanism.getDefaultInstance() : mech_;
  }
  /** <code>.grep11.Mechanism Mech = 1;</code> */
  @java.lang.Override
  public com.ibm.crypto.grep11.grpc.MechanismOrBuilder getMechOrBuilder() {
    return getMech();
  }

  public static final int PUBKEYTEMPLATE_FIELD_NUMBER = 2;

  private static final class PubKeyTemplateDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<java.lang.Long, com.google.protobuf.ByteString>
        defaultEntry =
            com.google.protobuf.MapEntry
                .<java.lang.Long, com.google.protobuf.ByteString>newDefaultInstance(
                    com.ibm.crypto.grep11.grpc.Hsm
                        .internal_static_grep11_GenerateKeyPairRequest_PubKeyTemplateEntry_descriptor,
                    com.google.protobuf.WireFormat.FieldType.UINT64,
                    0L,
                    com.google.protobuf.WireFormat.FieldType.BYTES,
                    com.google.protobuf.ByteString.EMPTY);
  }

  private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
      pubKeyTemplate_;

  private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
      internalGetPubKeyTemplate() {
    if (pubKeyTemplate_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PubKeyTemplateDefaultEntryHolder.defaultEntry);
    }
    return pubKeyTemplate_;
  }

  public int getPubKeyTemplateCount() {
    return internalGetPubKeyTemplate().getMap().size();
  }
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
   */
  @java.lang.Override
  public boolean containsPubKeyTemplate(long key) {

    return internalGetPubKeyTemplate().getMap().containsKey(key);
  }
  /** Use {@link #getPubKeyTemplateMap()} instead. */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getPubKeyTemplate() {
    return getPubKeyTemplateMap();
  }
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getPubKeyTemplateMap() {
    return internalGetPubKeyTemplate().getMap();
  }
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPubKeyTemplateOrDefault(
      long key, com.google.protobuf.ByteString defaultValue) {

    java.util.Map<java.lang.Long, com.google.protobuf.ByteString> map =
        internalGetPubKeyTemplate().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPubKeyTemplateOrThrow(long key) {

    java.util.Map<java.lang.Long, com.google.protobuf.ByteString> map =
        internalGetPubKeyTemplate().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PRIVKEYTEMPLATE_FIELD_NUMBER = 3;

  private static final class PrivKeyTemplateDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<java.lang.Long, com.google.protobuf.ByteString>
        defaultEntry =
            com.google.protobuf.MapEntry
                .<java.lang.Long, com.google.protobuf.ByteString>newDefaultInstance(
                    com.ibm.crypto.grep11.grpc.Hsm
                        .internal_static_grep11_GenerateKeyPairRequest_PrivKeyTemplateEntry_descriptor,
                    com.google.protobuf.WireFormat.FieldType.UINT64,
                    0L,
                    com.google.protobuf.WireFormat.FieldType.BYTES,
                    com.google.protobuf.ByteString.EMPTY);
  }

  private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
      privKeyTemplate_;

  private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
      internalGetPrivKeyTemplate() {
    if (privKeyTemplate_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PrivKeyTemplateDefaultEntryHolder.defaultEntry);
    }
    return privKeyTemplate_;
  }

  public int getPrivKeyTemplateCount() {
    return internalGetPrivKeyTemplate().getMap().size();
  }
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
   */
  @java.lang.Override
  public boolean containsPrivKeyTemplate(long key) {

    return internalGetPrivKeyTemplate().getMap().containsKey(key);
  }
  /** Use {@link #getPrivKeyTemplateMap()} instead. */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getPrivKeyTemplate() {
    return getPrivKeyTemplateMap();
  }
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getPrivKeyTemplateMap() {
    return internalGetPrivKeyTemplate().getMap();
  }
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPrivKeyTemplateOrDefault(
      long key, com.google.protobuf.ByteString defaultValue) {

    java.util.Map<java.lang.Long, com.google.protobuf.ByteString> map =
        internalGetPrivKeyTemplate().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPrivKeyTemplateOrThrow(long key) {

    java.util.Map<java.lang.Long, com.google.protobuf.ByteString> map =
        internalGetPrivKeyTemplate().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PRIVKEYID_FIELD_NUMBER = 5;
  private volatile java.lang.Object privKeyId_;
  /**
   * <code>string PrivKeyId = 5;</code>
   *
   * @return The privKeyId.
   */
  @java.lang.Override
  public java.lang.String getPrivKeyId() {
    java.lang.Object ref = privKeyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      privKeyId_ = s;
      return s;
    }
  }
  /**
   * <code>string PrivKeyId = 5;</code>
   *
   * @return The bytes for privKeyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPrivKeyIdBytes() {
    java.lang.Object ref = privKeyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      privKeyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBKEYID_FIELD_NUMBER = 6;
  private volatile java.lang.Object pubKeyId_;
  /**
   * <code>string PubKeyId = 6;</code>
   *
   * @return The pubKeyId.
   */
  @java.lang.Override
  public java.lang.String getPubKeyId() {
    java.lang.Object ref = pubKeyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pubKeyId_ = s;
      return s;
    }
  }
  /**
   * <code>string PubKeyId = 6;</code>
   *
   * @return The bytes for pubKeyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPubKeyIdBytes() {
    java.lang.Object ref = pubKeyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      pubKeyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (mech_ != null) {
      output.writeMessage(1, getMech());
    }
    com.google.protobuf.GeneratedMessageV3.serializeLongMapTo(
        output, internalGetPubKeyTemplate(), PubKeyTemplateDefaultEntryHolder.defaultEntry, 2);
    com.google.protobuf.GeneratedMessageV3.serializeLongMapTo(
        output, internalGetPrivKeyTemplate(), PrivKeyTemplateDefaultEntryHolder.defaultEntry, 3);
    if (!getPrivKeyIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, privKeyId_);
    }
    if (!getPubKeyIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, pubKeyId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mech_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getMech());
    }
    for (java.util.Map.Entry<java.lang.Long, com.google.protobuf.ByteString> entry :
        internalGetPubKeyTemplate().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, com.google.protobuf.ByteString>
          pubKeyTemplate__ =
              PubKeyTemplateDefaultEntryHolder.defaultEntry
                  .newBuilderForType()
                  .setKey(entry.getKey())
                  .setValue(entry.getValue())
                  .build();
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, pubKeyTemplate__);
    }
    for (java.util.Map.Entry<java.lang.Long, com.google.protobuf.ByteString> entry :
        internalGetPrivKeyTemplate().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, com.google.protobuf.ByteString>
          privKeyTemplate__ =
              PrivKeyTemplateDefaultEntryHolder.defaultEntry
                  .newBuilderForType()
                  .setKey(entry.getKey())
                  .setValue(entry.getValue())
                  .build();
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, privKeyTemplate__);
    }
    if (!getPrivKeyIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, privKeyId_);
    }
    if (!getPubKeyIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, pubKeyId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest)) {
      return super.equals(obj);
    }
    com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest other =
        (com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest) obj;

    if (hasMech() != other.hasMech()) return false;
    if (hasMech()) {
      if (!getMech().equals(other.getMech())) return false;
    }
    if (!internalGetPubKeyTemplate().equals(other.internalGetPubKeyTemplate())) return false;
    if (!internalGetPrivKeyTemplate().equals(other.internalGetPrivKeyTemplate())) return false;
    if (!getPrivKeyId().equals(other.getPrivKeyId())) return false;
    if (!getPubKeyId().equals(other.getPubKeyId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMech()) {
      hash = (37 * hash) + MECH_FIELD_NUMBER;
      hash = (53 * hash) + getMech().hashCode();
    }
    if (!internalGetPubKeyTemplate().getMap().isEmpty()) {
      hash = (37 * hash) + PUBKEYTEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPubKeyTemplate().hashCode();
    }
    if (!internalGetPrivKeyTemplate().getMap().isEmpty()) {
      hash = (37 * hash) + PRIVKEYTEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPrivKeyTemplate().hashCode();
    }
    hash = (37 * hash) + PRIVKEYID_FIELD_NUMBER;
    hash = (53 * hash) + getPrivKeyId().hashCode();
    hash = (37 * hash) + PUBKEYID_FIELD_NUMBER;
    hash = (53 * hash) + getPubKeyId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code grep11.GenerateKeyPairRequest} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:grep11.GenerateKeyPairRequest)
      com.ibm.crypto.grep11.grpc.GenerateKeyPairRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.ibm.crypto.grep11.grpc.Hsm
          .internal_static_grep11_GenerateKeyPairRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(int number) {
      switch (number) {
        case 2:
          return internalGetPubKeyTemplate();
        case 3:
          return internalGetPrivKeyTemplate();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
      switch (number) {
        case 2:
          return internalGetMutablePubKeyTemplate();
        case 3:
          return internalGetMutablePrivKeyTemplate();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ibm.crypto.grep11.grpc.Hsm
          .internal_static_grep11_GenerateKeyPairRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest.class,
              com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest.Builder.class);
    }

    // Construct using com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (mechBuilder_ == null) {
        mech_ = null;
      } else {
        mech_ = null;
        mechBuilder_ = null;
      }
      internalGetMutablePubKeyTemplate().clear();
      internalGetMutablePrivKeyTemplate().clear();
      privKeyId_ = "";

      pubKeyId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.ibm.crypto.grep11.grpc.Hsm
          .internal_static_grep11_GenerateKeyPairRequest_descriptor;
    }

    @java.lang.Override
    public com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest getDefaultInstanceForType() {
      return com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest build() {
      com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest buildPartial() {
      com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest result =
          new com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest(this);
      int from_bitField0_ = bitField0_;
      if (mechBuilder_ == null) {
        result.mech_ = mech_;
      } else {
        result.mech_ = mechBuilder_.build();
      }
      result.pubKeyTemplate_ = internalGetPubKeyTemplate();
      result.pubKeyTemplate_.makeImmutable();
      result.privKeyTemplate_ = internalGetPrivKeyTemplate();
      result.privKeyTemplate_.makeImmutable();
      result.privKeyId_ = privKeyId_;
      result.pubKeyId_ = pubKeyId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest) {
        return mergeFrom((com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest other) {
      if (other == com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest.getDefaultInstance())
        return this;
      if (other.hasMech()) {
        mergeMech(other.getMech());
      }
      internalGetMutablePubKeyTemplate().mergeFrom(other.internalGetPubKeyTemplate());
      internalGetMutablePrivKeyTemplate().mergeFrom(other.internalGetPrivKeyTemplate());
      if (!other.getPrivKeyId().isEmpty()) {
        privKeyId_ = other.privKeyId_;
        onChanged();
      }
      if (!other.getPubKeyId().isEmpty()) {
        pubKeyId_ = other.pubKeyId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private com.ibm.crypto.grep11.grpc.Mechanism mech_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.ibm.crypto.grep11.grpc.Mechanism,
            com.ibm.crypto.grep11.grpc.Mechanism.Builder,
            com.ibm.crypto.grep11.grpc.MechanismOrBuilder>
        mechBuilder_;
    /**
     * <code>.grep11.Mechanism Mech = 1;</code>
     *
     * @return Whether the mech field is set.
     */
    public boolean hasMech() {
      return mechBuilder_ != null || mech_ != null;
    }
    /**
     * <code>.grep11.Mechanism Mech = 1;</code>
     *
     * @return The mech.
     */
    public com.ibm.crypto.grep11.grpc.Mechanism getMech() {
      if (mechBuilder_ == null) {
        return mech_ == null ? com.ibm.crypto.grep11.grpc.Mechanism.getDefaultInstance() : mech_;
      } else {
        return mechBuilder_.getMessage();
      }
    }
    /** <code>.grep11.Mechanism Mech = 1;</code> */
    public Builder setMech(com.ibm.crypto.grep11.grpc.Mechanism value) {
      if (mechBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mech_ = value;
        onChanged();
      } else {
        mechBuilder_.setMessage(value);
      }

      return this;
    }
    /** <code>.grep11.Mechanism Mech = 1;</code> */
    public Builder setMech(com.ibm.crypto.grep11.grpc.Mechanism.Builder builderForValue) {
      if (mechBuilder_ == null) {
        mech_ = builderForValue.build();
        onChanged();
      } else {
        mechBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /** <code>.grep11.Mechanism Mech = 1;</code> */
    public Builder mergeMech(com.ibm.crypto.grep11.grpc.Mechanism value) {
      if (mechBuilder_ == null) {
        if (mech_ != null) {
          mech_ =
              com.ibm.crypto.grep11.grpc.Mechanism.newBuilder(mech_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          mech_ = value;
        }
        onChanged();
      } else {
        mechBuilder_.mergeFrom(value);
      }

      return this;
    }
    /** <code>.grep11.Mechanism Mech = 1;</code> */
    public Builder clearMech() {
      if (mechBuilder_ == null) {
        mech_ = null;
        onChanged();
      } else {
        mech_ = null;
        mechBuilder_ = null;
      }

      return this;
    }
    /** <code>.grep11.Mechanism Mech = 1;</code> */
    public com.ibm.crypto.grep11.grpc.Mechanism.Builder getMechBuilder() {

      onChanged();
      return getMechFieldBuilder().getBuilder();
    }
    /** <code>.grep11.Mechanism Mech = 1;</code> */
    public com.ibm.crypto.grep11.grpc.MechanismOrBuilder getMechOrBuilder() {
      if (mechBuilder_ != null) {
        return mechBuilder_.getMessageOrBuilder();
      } else {
        return mech_ == null ? com.ibm.crypto.grep11.grpc.Mechanism.getDefaultInstance() : mech_;
      }
    }
    /** <code>.grep11.Mechanism Mech = 1;</code> */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.ibm.crypto.grep11.grpc.Mechanism,
            com.ibm.crypto.grep11.grpc.Mechanism.Builder,
            com.ibm.crypto.grep11.grpc.MechanismOrBuilder>
        getMechFieldBuilder() {
      if (mechBuilder_ == null) {
        mechBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.ibm.crypto.grep11.grpc.Mechanism,
                com.ibm.crypto.grep11.grpc.Mechanism.Builder,
                com.ibm.crypto.grep11.grpc.MechanismOrBuilder>(
                getMech(), getParentForChildren(), isClean());
        mech_ = null;
      }
      return mechBuilder_;
    }

    private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
        pubKeyTemplate_;

    private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
        internalGetPubKeyTemplate() {
      if (pubKeyTemplate_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PubKeyTemplateDefaultEntryHolder.defaultEntry);
      }
      return pubKeyTemplate_;
    }

    private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
        internalGetMutablePubKeyTemplate() {
      onChanged();
      ;
      if (pubKeyTemplate_ == null) {
        pubKeyTemplate_ =
            com.google.protobuf.MapField.newMapField(PubKeyTemplateDefaultEntryHolder.defaultEntry);
      }
      if (!pubKeyTemplate_.isMutable()) {
        pubKeyTemplate_ = pubKeyTemplate_.copy();
      }
      return pubKeyTemplate_;
    }

    public int getPubKeyTemplateCount() {
      return internalGetPubKeyTemplate().getMap().size();
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
     */
    @java.lang.Override
    public boolean containsPubKeyTemplate(long key) {

      return internalGetPubKeyTemplate().getMap().containsKey(key);
    }
    /** Use {@link #getPubKeyTemplateMap()} instead. */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getPubKeyTemplate() {
      return getPubKeyTemplateMap();
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getPubKeyTemplateMap() {
      return internalGetPubKeyTemplate().getMap();
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPubKeyTemplateOrDefault(
        long key, com.google.protobuf.ByteString defaultValue) {

      java.util.Map<java.lang.Long, com.google.protobuf.ByteString> map =
          internalGetPubKeyTemplate().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPubKeyTemplateOrThrow(long key) {

      java.util.Map<java.lang.Long, com.google.protobuf.ByteString> map =
          internalGetPubKeyTemplate().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearPubKeyTemplate() {
      internalGetMutablePubKeyTemplate().getMutableMap().clear();
      return this;
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
     */
    public Builder removePubKeyTemplate(long key) {

      internalGetMutablePubKeyTemplate().getMutableMap().remove(key);
      return this;
    }
    /** Use alternate mutation accessors instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, com.google.protobuf.ByteString>
        getMutablePubKeyTemplate() {
      return internalGetMutablePubKeyTemplate().getMutableMap();
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
     */
    public Builder putPubKeyTemplate(long key, com.google.protobuf.ByteString value) {

      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      internalGetMutablePubKeyTemplate().getMutableMap().put(key, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PubKeyTemplate = 2;</code>
     */
    public Builder putAllPubKeyTemplate(
        java.util.Map<java.lang.Long, com.google.protobuf.ByteString> values) {
      internalGetMutablePubKeyTemplate().getMutableMap().putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
        privKeyTemplate_;

    private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
        internalGetPrivKeyTemplate() {
      if (privKeyTemplate_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PrivKeyTemplateDefaultEntryHolder.defaultEntry);
      }
      return privKeyTemplate_;
    }

    private com.google.protobuf.MapField<java.lang.Long, com.google.protobuf.ByteString>
        internalGetMutablePrivKeyTemplate() {
      onChanged();
      ;
      if (privKeyTemplate_ == null) {
        privKeyTemplate_ =
            com.google.protobuf.MapField.newMapField(
                PrivKeyTemplateDefaultEntryHolder.defaultEntry);
      }
      if (!privKeyTemplate_.isMutable()) {
        privKeyTemplate_ = privKeyTemplate_.copy();
      }
      return privKeyTemplate_;
    }

    public int getPrivKeyTemplateCount() {
      return internalGetPrivKeyTemplate().getMap().size();
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
     */
    @java.lang.Override
    public boolean containsPrivKeyTemplate(long key) {

      return internalGetPrivKeyTemplate().getMap().containsKey(key);
    }
    /** Use {@link #getPrivKeyTemplateMap()} instead. */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getPrivKeyTemplate() {
      return getPrivKeyTemplateMap();
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getPrivKeyTemplateMap() {
      return internalGetPrivKeyTemplate().getMap();
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivKeyTemplateOrDefault(
        long key, com.google.protobuf.ByteString defaultValue) {

      java.util.Map<java.lang.Long, com.google.protobuf.ByteString> map =
          internalGetPrivKeyTemplate().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivKeyTemplateOrThrow(long key) {

      java.util.Map<java.lang.Long, com.google.protobuf.ByteString> map =
          internalGetPrivKeyTemplate().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearPrivKeyTemplate() {
      internalGetMutablePrivKeyTemplate().getMutableMap().clear();
      return this;
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
     */
    public Builder removePrivKeyTemplate(long key) {

      internalGetMutablePrivKeyTemplate().getMutableMap().remove(key);
      return this;
    }
    /** Use alternate mutation accessors instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, com.google.protobuf.ByteString>
        getMutablePrivKeyTemplate() {
      return internalGetMutablePrivKeyTemplate().getMutableMap();
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
     */
    public Builder putPrivKeyTemplate(long key, com.google.protobuf.ByteString value) {

      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      internalGetMutablePrivKeyTemplate().getMutableMap().put(key, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
     * </pre>
     *
     * <code>map&lt;uint64, bytes&gt; PrivKeyTemplate = 3;</code>
     */
    public Builder putAllPrivKeyTemplate(
        java.util.Map<java.lang.Long, com.google.protobuf.ByteString> values) {
      internalGetMutablePrivKeyTemplate().getMutableMap().putAll(values);
      return this;
    }

    private java.lang.Object privKeyId_ = "";
    /**
     * <code>string PrivKeyId = 5;</code>
     *
     * @return The privKeyId.
     */
    public java.lang.String getPrivKeyId() {
      java.lang.Object ref = privKeyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        privKeyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string PrivKeyId = 5;</code>
     *
     * @return The bytes for privKeyId.
     */
    public com.google.protobuf.ByteString getPrivKeyIdBytes() {
      java.lang.Object ref = privKeyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        privKeyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string PrivKeyId = 5;</code>
     *
     * @param value The privKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setPrivKeyId(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      privKeyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string PrivKeyId = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearPrivKeyId() {

      privKeyId_ = getDefaultInstance().getPrivKeyId();
      onChanged();
      return this;
    }
    /**
     * <code>string PrivKeyId = 5;</code>
     *
     * @param value The bytes for privKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setPrivKeyIdBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      privKeyId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pubKeyId_ = "";
    /**
     * <code>string PubKeyId = 6;</code>
     *
     * @return The pubKeyId.
     */
    public java.lang.String getPubKeyId() {
      java.lang.Object ref = pubKeyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pubKeyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string PubKeyId = 6;</code>
     *
     * @return The bytes for pubKeyId.
     */
    public com.google.protobuf.ByteString getPubKeyIdBytes() {
      java.lang.Object ref = pubKeyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        pubKeyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string PubKeyId = 6;</code>
     *
     * @param value The pubKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setPubKeyId(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      pubKeyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string PubKeyId = 6;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearPubKeyId() {

      pubKeyId_ = getDefaultInstance().getPubKeyId();
      onChanged();
      return this;
    }
    /**
     * <code>string PubKeyId = 6;</code>
     *
     * @param value The bytes for pubKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setPubKeyIdBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      pubKeyId_ = value;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:grep11.GenerateKeyPairRequest)
  }

  // @@protoc_insertion_point(class_scope:grep11.GenerateKeyPairRequest)
  private static final com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest();
  }

  public static com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateKeyPairRequest> PARSER =
      new com.google.protobuf.AbstractParser<GenerateKeyPairRequest>() {
        @java.lang.Override
        public GenerateKeyPairRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new GenerateKeyPairRequest(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<GenerateKeyPairRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateKeyPairRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ibm.crypto.grep11.grpc.GenerateKeyPairRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
