// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface GetAttributeValueRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.GetAttributeValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Object = 1;</code>
   *
   * @return The object.
   */
  com.google.protobuf.ByteString getObject();

  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; Attributes = 2;</code>
   */
  int getAttributesCount();
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; Attributes = 2;</code>
   */
  boolean containsAttributes(long key);
  /** Use {@link #getAttributesMap()} instead. */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getAttributes();
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; Attributes = 2;</code>
   */
  java.util.Map<java.lang.Long, com.google.protobuf.ByteString> getAttributesMap();
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; Attributes = 2;</code>
   */
  com.google.protobuf.ByteString getAttributesOrDefault(
      long key, com.google.protobuf.ByteString defaultValue);
  /**
   *
   *
   * <pre>
   * [(gogoproto.castkey) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Attribute"];
   * </pre>
   *
   * <code>map&lt;uint64, bytes&gt; Attributes = 2;</code>
   */
  com.google.protobuf.ByteString getAttributesOrThrow(long key);
}
