// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface GetMechanismInfoResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.GetMechanismInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grep11.MechanismInfo MechInfo = 3;</code>
   *
   * @return Whether the mechInfo field is set.
   */
  boolean hasMechInfo();
  /**
   * <code>.grep11.MechanismInfo MechInfo = 3;</code>
   *
   * @return The mechInfo.
   */
  com.ibm.crypto.grep11.grpc.MechanismInfo getMechInfo();
  /** <code>.grep11.MechanismInfo MechInfo = 3;</code> */
  com.ibm.crypto.grep11.grpc.MechanismInfoOrBuilder getMechInfoOrBuilder();
}
