// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface Grep11ErrorOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.Grep11Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * [(gogoproto.casttype) = "github.com/ibm-developer/ibm-cloud-hyperprotectcrypto/golang/ep11.Return"];
   * </pre>
   *
   * <code>uint64 Code = 1;</code>
   *
   * @return The code.
   */
  long getCode();

  /**
   * <code>string Detail = 2;</code>
   *
   * @return The detail.
   */
  java.lang.String getDetail();
  /**
   * <code>string Detail = 2;</code>
   *
   * @return The bytes for detail.
   */
  com.google.protobuf.ByteString getDetailBytes();

  /**
   * <code>bool Retry = 3;</code>
   *
   * @return The retry.
   */
  boolean getRetry();
}
