// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public final class Hsm {
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateRandomRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateRandomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateRandomResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateRandomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestInitRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestInitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestInitResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestInitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestUpdateRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestUpdateResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestKeyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestKeyResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestFinalRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestFinalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestFinalResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestFinalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestSingleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestSingleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DigestSingleResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DigestSingleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptInitRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptInitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptInitResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptInitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptInitRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptInitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptInitResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptInitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptUpdateRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptUpdateResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptUpdateRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptUpdateResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptFinalRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptFinalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptFinalResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptFinalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptFinalRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptFinalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptFinalResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptFinalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptSingleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptSingleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_EncryptSingleResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_EncryptSingleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptSingleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptSingleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DecryptSingleResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DecryptSingleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignInitRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignInitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignInitResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignInitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifyInitRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifyInitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifyInitResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifyInitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignUpdateRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignUpdateResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifyUpdateRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifyUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifyUpdateResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifyUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignFinalRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignFinalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignFinalResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignFinalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifyFinalRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifyFinalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifyFinalResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifyFinalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifyResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignSingleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignSingleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SignSingleResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SignSingleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifySingleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifySingleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_VerifySingleResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_VerifySingleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateKeyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateKeyRequest_TemplateEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateKeyRequest_TemplateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateKeyResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateKeyPairRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateKeyPairRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateKeyPairRequest_PubKeyTemplateEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateKeyPairRequest_PubKeyTemplateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateKeyPairRequest_PrivKeyTemplateEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateKeyPairRequest_PrivKeyTemplateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GenerateKeyPairResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GenerateKeyPairResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_WrapKeyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_WrapKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_WrapKeyResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_WrapKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_UnwrapKeyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_UnwrapKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_UnwrapKeyRequest_TemplateEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_UnwrapKeyRequest_TemplateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_UnwrapKeyResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_UnwrapKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DeriveKeyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DeriveKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DeriveKeyRequest_TemplateEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DeriveKeyRequest_TemplateEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_DeriveKeyResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_DeriveKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GetMechanismListRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GetMechanismListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GetMechanismListResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GetMechanismListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GetMechanismInfoRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GetMechanismInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GetMechanismInfoResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GetMechanismInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GetAttributeValueRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GetAttributeValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GetAttributeValueRequest_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GetAttributeValueRequest_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GetAttributeValueResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GetAttributeValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_GetAttributeValueResponse_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_GetAttributeValueResponse_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SetAttributeValueRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SetAttributeValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SetAttributeValueRequest_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SetAttributeValueRequest_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_SetAttributeValueResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_SetAttributeValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_Mechanism_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_Mechanism_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_MechanismInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_MechanismInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grep11_Grep11Error_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grep11_Grep11Error_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\thsm.proto\022\006grep11\"$\n\025GenerateRandomReq"
          + "uest\022\013\n\003Len\030\001 \001(\004\"%\n\026GenerateRandomRespo"
          + "nse\022\013\n\003Rnd\030\001 \001(\014\"4\n\021DigestInitRequest\022\037\n"
          + "\004Mech\030\002 \001(\0132\021.grep11.Mechanism\"#\n\022Digest"
          + "InitResponse\022\r\n\005State\030\001 \001(\014\",\n\rDigestReq"
          + "uest\022\r\n\005State\030\001 \001(\014\022\014\n\004Data\030\002 \001(\014\" \n\016Dig"
          + "estResponse\022\016\n\006Digest\030\003 \001(\014\"2\n\023DigestUpd"
          + "ateRequest\022\r\n\005State\030\001 \001(\014\022\014\n\004Data\030\002 \001(\014\""
          + "%\n\024DigestUpdateResponse\022\r\n\005State\030\001 \001(\014\"."
          + "\n\020DigestKeyRequest\022\r\n\005State\030\001 \001(\014\022\013\n\003Key"
          + "\030\002 \001(\014\"\"\n\021DigestKeyResponse\022\r\n\005State\030\001 \001"
          + "(\014\"#\n\022DigestFinalRequest\022\r\n\005State\030\001 \001(\014\""
          + "%\n\023DigestFinalResponse\022\016\n\006Digest\030\002 \001(\014\"D"
          + "\n\023DigestSingleRequest\022\037\n\004Mech\030\001 \001(\0132\021.gr"
          + "ep11.Mechanism\022\014\n\004Data\030\002 \001(\014\"&\n\024DigestSi"
          + "ngleResponse\022\016\n\006Digest\030\003 \001(\014\"B\n\022EncryptI"
          + "nitRequest\022\037\n\004Mech\030\002 \001(\0132\021.grep11.Mechan"
          + "ism\022\013\n\003Key\030\003 \001(\014\"$\n\023EncryptInitResponse\022"
          + "\r\n\005State\030\001 \001(\014\"B\n\022DecryptInitRequest\022\037\n\004"
          + "Mech\030\002 \001(\0132\021.grep11.Mechanism\022\013\n\003Key\030\003 \001"
          + "(\014\"$\n\023DecryptInitResponse\022\r\n\005State\030\001 \001(\014"
          + "\"4\n\024EncryptUpdateRequest\022\r\n\005State\030\001 \001(\014\022"
          + "\r\n\005Plain\030\002 \001(\014\"8\n\025EncryptUpdateResponse\022"
          + "\r\n\005State\030\001 \001(\014\022\020\n\010Ciphered\030\003 \001(\014\"7\n\024Decr"
          + "yptUpdateRequest\022\r\n\005State\030\001 \001(\014\022\020\n\010Ciphe"
          + "red\030\002 \001(\014\"5\n\025DecryptUpdateResponse\022\r\n\005St"
          + "ate\030\001 \001(\014\022\r\n\005Plain\030\003 \001(\014\".\n\016EncryptReque"
          + "st\022\r\n\005State\030\001 \001(\014\022\r\n\005Plain\030\002 \001(\014\"#\n\017Encr"
          + "yptResponse\022\020\n\010Ciphered\030\003 \001(\014\"1\n\016Decrypt"
          + "Request\022\r\n\005State\030\001 \001(\014\022\020\n\010Ciphered\030\002 \001(\014"
          + "\" \n\017DecryptResponse\022\r\n\005Plain\030\003 \001(\014\"$\n\023En"
          + "cryptFinalRequest\022\r\n\005State\030\001 \001(\014\"(\n\024Encr"
          + "yptFinalResponse\022\020\n\010Ciphered\030\002 \001(\014\"$\n\023De"
          + "cryptFinalRequest\022\r\n\005State\030\001 \001(\014\"%\n\024Decr"
          + "yptFinalResponse\022\r\n\005Plain\030\002 \001(\014\"S\n\024Encry"
          + "ptSingleRequest\022\013\n\003Key\030\001 \001(\014\022\037\n\004Mech\030\002 \001"
          + "(\0132\021.grep11.Mechanism\022\r\n\005Plain\030\003 \001(\014\")\n\025"
          + "EncryptSingleResponse\022\020\n\010Ciphered\030\004 \001(\014\""
          + "V\n\024DecryptSingleRequest\022\013\n\003Key\030\001 \001(\014\022\037\n\004"
          + "Mech\030\002 \001(\0132\021.grep11.Mechanism\022\020\n\010Ciphere"
          + "d\030\003 \001(\014\"&\n\025DecryptSingleResponse\022\r\n\005Plai"
          + "n\030\004 \001(\014\"C\n\017SignInitRequest\022\037\n\004Mech\030\002 \001(\013"
          + "2\021.grep11.Mechanism\022\017\n\007PrivKey\030\003 \001(\014\"!\n\020"
          + "SignInitResponse\022\r\n\005State\030\001 \001(\014\"D\n\021Verif"
          + "yInitRequest\022\037\n\004Mech\030\002 \001(\0132\021.grep11.Mech"
          + "anism\022\016\n\006PubKey\030\003 \001(\014\"#\n\022VerifyInitRespo"
          + "nse\022\r\n\005State\030\001 \001(\014\"0\n\021SignUpdateRequest\022"
          + "\r\n\005State\030\001 \001(\014\022\014\n\004Data\030\002 \001(\014\"#\n\022SignUpda"
          + "teResponse\022\r\n\005State\030\001 \001(\014\"2\n\023VerifyUpdat"
          + "eRequest\022\r\n\005State\030\001 \001(\014\022\014\n\004Data\030\002 \001(\014\"%\n"
          + "\024VerifyUpdateResponse\022\r\n\005State\030\001 \001(\014\"!\n\020"
          + "SignFinalRequest\022\r\n\005State\030\001 \001(\014\"&\n\021SignF"
          + "inalResponse\022\021\n\tSignature\030\002 \001(\014\"6\n\022Verif"
          + "yFinalRequest\022\r\n\005State\030\001 \001(\014\022\021\n\tSignatur"
          + "e\030\002 \001(\014\"\025\n\023VerifyFinalResponse\"*\n\013SignRe"
          + "quest\022\r\n\005State\030\001 \001(\014\022\014\n\004Data\030\002 \001(\014\"!\n\014Si"
          + "gnResponse\022\021\n\tSignature\030\003 \001(\014\"?\n\rVerifyR"
          + "equest\022\r\n\005State\030\001 \001(\014\022\014\n\004Data\030\002 \001(\014\022\021\n\tS"
          + "ignature\030\003 \001(\014\"\020\n\016VerifyResponse\"S\n\021Sign"
          + "SingleRequest\022\017\n\007PrivKey\030\001 \001(\014\022\037\n\004Mech\030\002"
          + " \001(\0132\021.grep11.Mechanism\022\014\n\004Data\030\003 \001(\014\"\'\n"
          + "\022SignSingleResponse\022\021\n\tSignature\030\004 \001(\014\"g"
          + "\n\023VerifySingleRequest\022\016\n\006PubKey\030\001 \001(\014\022\037\n"
          + "\004Mech\030\002 \001(\0132\021.grep11.Mechanism\022\014\n\004Data\030\003"
          + " \001(\014\022\021\n\tSignature\030\004 \001(\014\"\026\n\024VerifySingleR"
          + "esponse\"\261\001\n\022GenerateKeyRequest\022\037\n\004Mech\030\001"
          + " \001(\0132\021.grep11.Mechanism\022:\n\010Template\030\002 \003("
          + "\0132(.grep11.GenerateKeyRequest.TemplateEn"
          + "try\022\r\n\005KeyId\030\004 \001(\t\032/\n\rTemplateEntry\022\013\n\003k"
          + "ey\030\001 \001(\004\022\r\n\005value\030\002 \001(\014:\0028\001\"4\n\023GenerateK"
          + "eyResponse\022\013\n\003Key\030\004 \001(\014\022\020\n\010CheckSum\030\005 \001("
          + "\014\"\347\002\n\026GenerateKeyPairRequest\022\037\n\004Mech\030\001 \001"
          + "(\0132\021.grep11.Mechanism\022J\n\016PubKeyTemplate\030"
          + "\002 \003(\01322.grep11.GenerateKeyPairRequest.Pu"
          + "bKeyTemplateEntry\022L\n\017PrivKeyTemplate\030\003 \003"
          + "(\01323.grep11.GenerateKeyPairRequest.PrivK"
          + "eyTemplateEntry\022\021\n\tPrivKeyId\030\005 \001(\t\022\020\n\010Pu"
          + "bKeyId\030\006 \001(\t\0325\n\023PubKeyTemplateEntry\022\013\n\003k"
          + "ey\030\001 \001(\004\022\r\n\005value\030\002 \001(\014:\0028\001\0326\n\024PrivKeyTe"
          + "mplateEntry\022\013\n\003key\030\001 \001(\004\022\r\n\005value\030\002 \001(\014:"
          + "\0028\001\":\n\027GenerateKeyPairResponse\022\017\n\007PrivKe"
          + "y\030\005 \001(\014\022\016\n\006PubKey\030\006 \001(\014\"[\n\016WrapKeyReques"
          + "t\022\013\n\003Key\030\001 \001(\014\022\013\n\003KeK\030\002 \001(\014\022\016\n\006MacKey\030\003 "
          + "\001(\014\022\037\n\004Mech\030\004 \001(\0132\021.grep11.Mechanism\"\"\n\017"
          + "WrapKeyResponse\022\017\n\007Wrapped\030\005 \001(\014\"\341\001\n\020Unw"
          + "rapKeyRequest\022\017\n\007Wrapped\030\001 \001(\014\022\013\n\003KeK\030\002 "
          + "\001(\014\022\016\n\006MacKey\030\003 \001(\014\022\037\n\004Mech\030\005 \001(\0132\021.grep"
          + "11.Mechanism\0228\n\010Template\030\006 \003(\0132&.grep11."
          + "UnwrapKeyRequest.TemplateEntry\022\023\n\013Unwrap"
          + "pedId\030\007 \001(\t\032/\n\rTemplateEntry\022\013\n\003key\030\001 \001("
          + "\004\022\r\n\005value\030\002 \001(\014:\0028\001\"8\n\021UnwrapKeyRespons"
          + "e\022\021\n\tUnwrapped\030\007 \001(\014\022\020\n\010CheckSum\030\010 \001(\014\"\317"
          + "\001\n\020DeriveKeyRequest\022\037\n\004Mech\030\001 \001(\0132\021.grep"
          + "11.Mechanism\0228\n\010Template\030\002 \003(\0132&.grep11."
          + "DeriveKeyRequest.TemplateEntry\022\017\n\007BaseKe"
          + "y\030\003 \001(\014\022\014\n\004Data\030\004 \001(\014\022\020\n\010NewKeyId\030\006 \001(\t\032"
          + "/\n\rTemplateEntry\022\013\n\003key\030\001 \001(\004\022\r\n\005value\030\002"
          + " \001(\014:\0028\001\"5\n\021DeriveKeyResponse\022\016\n\006NewKey\030"
          + "\006 \001(\014\022\020\n\010CheckSum\030\007 \001(\014\"\031\n\027GetMechanismL"
          + "istRequest\")\n\030GetMechanismListResponse\022\r"
          + "\n\005Mechs\030\002 \003(\004\"\'\n\027GetMechanismInfoRequest"
          + "\022\014\n\004Mech\030\002 \001(\004\"C\n\030GetMechanismInfoRespon"
          + "se\022\'\n\010MechInfo\030\003 \001(\0132\025.grep11.MechanismI"
          + "nfo\"\243\001\n\030GetAttributeValueRequest\022\016\n\006Obje"
          + "ct\030\001 \001(\014\022D\n\nAttributes\030\002 \003(\01320.grep11.Ge"
          + "tAttributeValueRequest.AttributesEntry\0321"
          + "\n\017AttributesEntry\022\013\n\003key\030\001 \001(\004\022\r\n\005value\030"
          + "\002 \001(\014:\0028\001\"\225\001\n\031GetAttributeValueResponse\022"
          + "E\n\nAttributes\030\002 \003(\01321.grep11.GetAttribut"
          + "eValueResponse.AttributesEntry\0321\n\017Attrib"
          + "utesEntry\022\013\n\003key\030\001 \001(\004\022\r\n\005value\030\002 \001(\014:\0028"
          + "\001\"\243\001\n\030SetAttributeValueRequest\022\016\n\006Object"
          + "\030\001 \001(\014\022D\n\nAttributes\030\002 \003(\01320.grep11.SetA"
          + "ttributeValueRequest.AttributesEntry\0321\n\017"
          + "AttributesEntry\022\013\n\003key\030\001 \001(\004\022\r\n\005value\030\002 "
          + "\001(\014:\0028\001\"+\n\031SetAttributeValueResponse\022\016\n\006"
          + "Object\030\001 \001(\014\"1\n\tMechanism\022\021\n\tMechanism\030\001"
          + " \001(\004\022\021\n\tParameter\030\002 \001(\014\"F\n\rMechanismInfo"
          + "\022\022\n\nMinKeySize\030\001 \001(\004\022\022\n\nMaxKeySize\030\002 \001(\004"
          + "\022\r\n\005Flags\030\003 \001(\004\":\n\013Grep11Error\022\014\n\004Code\030\001"
          + " \001(\004\022\016\n\006Detail\030\002 \001(\t\022\r\n\005Retry\030\003 \001(\0102\355\024\n\006"
          + "Crypto\022Q\n\016GenerateRandom\022\035.grep11.Genera"
          + "teRandomRequest\032\036.grep11.GenerateRandomR"
          + "esponse\"\000\022E\n\nDigestInit\022\031.grep11.DigestI"
          + "nitRequest\032\032.grep11.DigestInitResponse\"\000"
          + "\0229\n\006Digest\022\025.grep11.DigestRequest\032\026.grep"
          + "11.DigestResponse\"\000\022K\n\014DigestUpdate\022\033.gr"
          + "ep11.DigestUpdateRequest\032\034.grep11.Digest"
          + "UpdateResponse\"\000\022B\n\tDigestKey\022\030.grep11.D"
          + "igestKeyRequest\032\031.grep11.DigestKeyRespon"
          + "se\"\000\022H\n\013DigestFinal\022\032.grep11.DigestFinal"
          + "Request\032\033.grep11.DigestFinalResponse\"\000\022K"
          + "\n\014DigestSingle\022\033.grep11.DigestSingleRequ"
          + "est\032\034.grep11.DigestSingleResponse\"\000\022H\n\013E"
          + "ncryptInit\022\032.grep11.EncryptInitRequest\032\033"
          + ".grep11.EncryptInitResponse\"\000\022H\n\013Decrypt"
          + "Init\022\032.grep11.DecryptInitRequest\032\033.grep1"
          + "1.DecryptInitResponse\"\000\022N\n\rEncryptUpdate"
          + "\022\034.grep11.EncryptUpdateRequest\032\035.grep11."
          + "EncryptUpdateResponse\"\000\022N\n\rDecryptUpdate"
          + "\022\034.grep11.DecryptUpdateRequest\032\035.grep11."
          + "DecryptUpdateResponse\"\000\022<\n\007Encrypt\022\026.gre"
          + "p11.EncryptRequest\032\027.grep11.EncryptRespo"
          + "nse\"\000\022<\n\007Decrypt\022\026.grep11.DecryptRequest"
          + "\032\027.grep11.DecryptResponse\"\000\022K\n\014EncryptFi"
          + "nal\022\033.grep11.EncryptFinalRequest\032\034.grep1"
          + "1.EncryptFinalResponse\"\000\022K\n\014DecryptFinal"
          + "\022\033.grep11.DecryptFinalRequest\032\034.grep11.D"
          + "ecryptFinalResponse\"\000\022N\n\rEncryptSingle\022\034"
          + ".grep11.EncryptSingleRequest\032\035.grep11.En"
          + "cryptSingleResponse\"\000\022N\n\rDecryptSingle\022\034"
          + ".grep11.DecryptSingleRequest\032\035.grep11.De"
          + "cryptSingleResponse\"\000\022?\n\010SignInit\022\027.grep"
          + "11.SignInitRequest\032\030.grep11.SignInitResp"
          + "onse\"\000\022E\n\nVerifyInit\022\031.grep11.VerifyInit"
          + "Request\032\032.grep11.VerifyInitResponse\"\000\022E\n"
          + "\nSignUpdate\022\031.grep11.SignUpdateRequest\032\032"
          + ".grep11.SignUpdateResponse\"\000\022K\n\014VerifyUp"
          + "date\022\033.grep11.VerifyUpdateRequest\032\034.grep"
          + "11.VerifyUpdateResponse\"\000\022B\n\tSignFinal\022\030"
          + ".grep11.SignFinalRequest\032\031.grep11.SignFi"
          + "nalResponse\"\000\022H\n\013VerifyFinal\022\032.grep11.Ve"
          + "rifyFinalRequest\032\033.grep11.VerifyFinalRes"
          + "ponse\"\000\0223\n\004Sign\022\023.grep11.SignRequest\032\024.g"
          + "rep11.SignResponse\"\000\0229\n\006Verify\022\025.grep11."
          + "VerifyRequest\032\026.grep11.VerifyResponse\"\000\022"
          + "E\n\nSignSingle\022\031.grep11.SignSingleRequest"
          + "\032\032.grep11.SignSingleResponse\"\000\022K\n\014Verify"
          + "Single\022\033.grep11.VerifySingleRequest\032\034.gr"
          + "ep11.VerifySingleResponse\"\000\022H\n\013GenerateK"
          + "ey\022\032.grep11.GenerateKeyRequest\032\033.grep11."
          + "GenerateKeyResponse\"\000\022T\n\017GenerateKeyPair"
          + "\022\036.grep11.GenerateKeyPairRequest\032\037.grep1"
          + "1.GenerateKeyPairResponse\"\000\022<\n\007WrapKey\022\026"
          + ".grep11.WrapKeyRequest\032\027.grep11.WrapKeyR"
          + "esponse\"\000\022B\n\tUnwrapKey\022\030.grep11.UnwrapKe"
          + "yRequest\032\031.grep11.UnwrapKeyResponse\"\000\022B\n"
          + "\tDeriveKey\022\030.grep11.DeriveKeyRequest\032\031.g"
          + "rep11.DeriveKeyResponse\"\000\022W\n\020GetMechanis"
          + "mList\022\037.grep11.GetMechanismListRequest\032 "
          + ".grep11.GetMechanismListResponse\"\000\022W\n\020Ge"
          + "tMechanismInfo\022\037.grep11.GetMechanismInfo"
          + "Request\032 .grep11.GetMechanismInfoRespons"
          + "e\"\000\022Z\n\021GetAttributeValue\022 .grep11.GetAtt"
          + "ributeValueRequest\032!.grep11.GetAttribute"
          + "ValueResponse\"\000\022Z\n\021SetAttributeValue\022 .g"
          + "rep11.SetAttributeValueRequest\032!.grep11."
          + "SetAttributeValueResponse\"\000B\036\n\032com.ibm.c"
          + "rypto.grep11.grpcP\001b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_grep11_GenerateRandomRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_grep11_GenerateRandomRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateRandomRequest_descriptor,
            new java.lang.String[] {
              "Len",
            });
    internal_static_grep11_GenerateRandomResponse_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_grep11_GenerateRandomResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateRandomResponse_descriptor,
            new java.lang.String[] {
              "Rnd",
            });
    internal_static_grep11_DigestInitRequest_descriptor = getDescriptor().getMessageTypes().get(2);
    internal_static_grep11_DigestInitRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestInitRequest_descriptor,
            new java.lang.String[] {
              "Mech",
            });
    internal_static_grep11_DigestInitResponse_descriptor = getDescriptor().getMessageTypes().get(3);
    internal_static_grep11_DigestInitResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestInitResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_DigestRequest_descriptor = getDescriptor().getMessageTypes().get(4);
    internal_static_grep11_DigestRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestRequest_descriptor,
            new java.lang.String[] {
              "State", "Data",
            });
    internal_static_grep11_DigestResponse_descriptor = getDescriptor().getMessageTypes().get(5);
    internal_static_grep11_DigestResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestResponse_descriptor,
            new java.lang.String[] {
              "Digest",
            });
    internal_static_grep11_DigestUpdateRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_grep11_DigestUpdateRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestUpdateRequest_descriptor,
            new java.lang.String[] {
              "State", "Data",
            });
    internal_static_grep11_DigestUpdateResponse_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_grep11_DigestUpdateResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestUpdateResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_DigestKeyRequest_descriptor = getDescriptor().getMessageTypes().get(8);
    internal_static_grep11_DigestKeyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestKeyRequest_descriptor,
            new java.lang.String[] {
              "State", "Key",
            });
    internal_static_grep11_DigestKeyResponse_descriptor = getDescriptor().getMessageTypes().get(9);
    internal_static_grep11_DigestKeyResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestKeyResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_DigestFinalRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_grep11_DigestFinalRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestFinalRequest_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_DigestFinalResponse_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_grep11_DigestFinalResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestFinalResponse_descriptor,
            new java.lang.String[] {
              "Digest",
            });
    internal_static_grep11_DigestSingleRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_grep11_DigestSingleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestSingleRequest_descriptor,
            new java.lang.String[] {
              "Mech", "Data",
            });
    internal_static_grep11_DigestSingleResponse_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_grep11_DigestSingleResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DigestSingleResponse_descriptor,
            new java.lang.String[] {
              "Digest",
            });
    internal_static_grep11_EncryptInitRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_grep11_EncryptInitRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptInitRequest_descriptor,
            new java.lang.String[] {
              "Mech", "Key",
            });
    internal_static_grep11_EncryptInitResponse_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_grep11_EncryptInitResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptInitResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_DecryptInitRequest_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_grep11_DecryptInitRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptInitRequest_descriptor,
            new java.lang.String[] {
              "Mech", "Key",
            });
    internal_static_grep11_DecryptInitResponse_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_grep11_DecryptInitResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptInitResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_EncryptUpdateRequest_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_grep11_EncryptUpdateRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptUpdateRequest_descriptor,
            new java.lang.String[] {
              "State", "Plain",
            });
    internal_static_grep11_EncryptUpdateResponse_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_grep11_EncryptUpdateResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptUpdateResponse_descriptor,
            new java.lang.String[] {
              "State", "Ciphered",
            });
    internal_static_grep11_DecryptUpdateRequest_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_grep11_DecryptUpdateRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptUpdateRequest_descriptor,
            new java.lang.String[] {
              "State", "Ciphered",
            });
    internal_static_grep11_DecryptUpdateResponse_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_grep11_DecryptUpdateResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptUpdateResponse_descriptor,
            new java.lang.String[] {
              "State", "Plain",
            });
    internal_static_grep11_EncryptRequest_descriptor = getDescriptor().getMessageTypes().get(22);
    internal_static_grep11_EncryptRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptRequest_descriptor,
            new java.lang.String[] {
              "State", "Plain",
            });
    internal_static_grep11_EncryptResponse_descriptor = getDescriptor().getMessageTypes().get(23);
    internal_static_grep11_EncryptResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptResponse_descriptor,
            new java.lang.String[] {
              "Ciphered",
            });
    internal_static_grep11_DecryptRequest_descriptor = getDescriptor().getMessageTypes().get(24);
    internal_static_grep11_DecryptRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptRequest_descriptor,
            new java.lang.String[] {
              "State", "Ciphered",
            });
    internal_static_grep11_DecryptResponse_descriptor = getDescriptor().getMessageTypes().get(25);
    internal_static_grep11_DecryptResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptResponse_descriptor,
            new java.lang.String[] {
              "Plain",
            });
    internal_static_grep11_EncryptFinalRequest_descriptor =
        getDescriptor().getMessageTypes().get(26);
    internal_static_grep11_EncryptFinalRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptFinalRequest_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_EncryptFinalResponse_descriptor =
        getDescriptor().getMessageTypes().get(27);
    internal_static_grep11_EncryptFinalResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptFinalResponse_descriptor,
            new java.lang.String[] {
              "Ciphered",
            });
    internal_static_grep11_DecryptFinalRequest_descriptor =
        getDescriptor().getMessageTypes().get(28);
    internal_static_grep11_DecryptFinalRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptFinalRequest_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_DecryptFinalResponse_descriptor =
        getDescriptor().getMessageTypes().get(29);
    internal_static_grep11_DecryptFinalResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptFinalResponse_descriptor,
            new java.lang.String[] {
              "Plain",
            });
    internal_static_grep11_EncryptSingleRequest_descriptor =
        getDescriptor().getMessageTypes().get(30);
    internal_static_grep11_EncryptSingleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptSingleRequest_descriptor,
            new java.lang.String[] {
              "Key", "Mech", "Plain",
            });
    internal_static_grep11_EncryptSingleResponse_descriptor =
        getDescriptor().getMessageTypes().get(31);
    internal_static_grep11_EncryptSingleResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_EncryptSingleResponse_descriptor,
            new java.lang.String[] {
              "Ciphered",
            });
    internal_static_grep11_DecryptSingleRequest_descriptor =
        getDescriptor().getMessageTypes().get(32);
    internal_static_grep11_DecryptSingleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptSingleRequest_descriptor,
            new java.lang.String[] {
              "Key", "Mech", "Ciphered",
            });
    internal_static_grep11_DecryptSingleResponse_descriptor =
        getDescriptor().getMessageTypes().get(33);
    internal_static_grep11_DecryptSingleResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DecryptSingleResponse_descriptor,
            new java.lang.String[] {
              "Plain",
            });
    internal_static_grep11_SignInitRequest_descriptor = getDescriptor().getMessageTypes().get(34);
    internal_static_grep11_SignInitRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignInitRequest_descriptor,
            new java.lang.String[] {
              "Mech", "PrivKey",
            });
    internal_static_grep11_SignInitResponse_descriptor = getDescriptor().getMessageTypes().get(35);
    internal_static_grep11_SignInitResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignInitResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_VerifyInitRequest_descriptor = getDescriptor().getMessageTypes().get(36);
    internal_static_grep11_VerifyInitRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifyInitRequest_descriptor,
            new java.lang.String[] {
              "Mech", "PubKey",
            });
    internal_static_grep11_VerifyInitResponse_descriptor =
        getDescriptor().getMessageTypes().get(37);
    internal_static_grep11_VerifyInitResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifyInitResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_SignUpdateRequest_descriptor = getDescriptor().getMessageTypes().get(38);
    internal_static_grep11_SignUpdateRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignUpdateRequest_descriptor,
            new java.lang.String[] {
              "State", "Data",
            });
    internal_static_grep11_SignUpdateResponse_descriptor =
        getDescriptor().getMessageTypes().get(39);
    internal_static_grep11_SignUpdateResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignUpdateResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_VerifyUpdateRequest_descriptor =
        getDescriptor().getMessageTypes().get(40);
    internal_static_grep11_VerifyUpdateRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifyUpdateRequest_descriptor,
            new java.lang.String[] {
              "State", "Data",
            });
    internal_static_grep11_VerifyUpdateResponse_descriptor =
        getDescriptor().getMessageTypes().get(41);
    internal_static_grep11_VerifyUpdateResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifyUpdateResponse_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_SignFinalRequest_descriptor = getDescriptor().getMessageTypes().get(42);
    internal_static_grep11_SignFinalRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignFinalRequest_descriptor,
            new java.lang.String[] {
              "State",
            });
    internal_static_grep11_SignFinalResponse_descriptor = getDescriptor().getMessageTypes().get(43);
    internal_static_grep11_SignFinalResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignFinalResponse_descriptor,
            new java.lang.String[] {
              "Signature",
            });
    internal_static_grep11_VerifyFinalRequest_descriptor =
        getDescriptor().getMessageTypes().get(44);
    internal_static_grep11_VerifyFinalRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifyFinalRequest_descriptor,
            new java.lang.String[] {
              "State", "Signature",
            });
    internal_static_grep11_VerifyFinalResponse_descriptor =
        getDescriptor().getMessageTypes().get(45);
    internal_static_grep11_VerifyFinalResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifyFinalResponse_descriptor, new java.lang.String[] {});
    internal_static_grep11_SignRequest_descriptor = getDescriptor().getMessageTypes().get(46);
    internal_static_grep11_SignRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignRequest_descriptor,
            new java.lang.String[] {
              "State", "Data",
            });
    internal_static_grep11_SignResponse_descriptor = getDescriptor().getMessageTypes().get(47);
    internal_static_grep11_SignResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignResponse_descriptor,
            new java.lang.String[] {
              "Signature",
            });
    internal_static_grep11_VerifyRequest_descriptor = getDescriptor().getMessageTypes().get(48);
    internal_static_grep11_VerifyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifyRequest_descriptor,
            new java.lang.String[] {
              "State", "Data", "Signature",
            });
    internal_static_grep11_VerifyResponse_descriptor = getDescriptor().getMessageTypes().get(49);
    internal_static_grep11_VerifyResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifyResponse_descriptor, new java.lang.String[] {});
    internal_static_grep11_SignSingleRequest_descriptor = getDescriptor().getMessageTypes().get(50);
    internal_static_grep11_SignSingleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignSingleRequest_descriptor,
            new java.lang.String[] {
              "PrivKey", "Mech", "Data",
            });
    internal_static_grep11_SignSingleResponse_descriptor =
        getDescriptor().getMessageTypes().get(51);
    internal_static_grep11_SignSingleResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SignSingleResponse_descriptor,
            new java.lang.String[] {
              "Signature",
            });
    internal_static_grep11_VerifySingleRequest_descriptor =
        getDescriptor().getMessageTypes().get(52);
    internal_static_grep11_VerifySingleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifySingleRequest_descriptor,
            new java.lang.String[] {
              "PubKey", "Mech", "Data", "Signature",
            });
    internal_static_grep11_VerifySingleResponse_descriptor =
        getDescriptor().getMessageTypes().get(53);
    internal_static_grep11_VerifySingleResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_VerifySingleResponse_descriptor, new java.lang.String[] {});
    internal_static_grep11_GenerateKeyRequest_descriptor =
        getDescriptor().getMessageTypes().get(54);
    internal_static_grep11_GenerateKeyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateKeyRequest_descriptor,
            new java.lang.String[] {
              "Mech", "Template", "KeyId",
            });
    internal_static_grep11_GenerateKeyRequest_TemplateEntry_descriptor =
        internal_static_grep11_GenerateKeyRequest_descriptor.getNestedTypes().get(0);
    internal_static_grep11_GenerateKeyRequest_TemplateEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateKeyRequest_TemplateEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_grep11_GenerateKeyResponse_descriptor =
        getDescriptor().getMessageTypes().get(55);
    internal_static_grep11_GenerateKeyResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateKeyResponse_descriptor,
            new java.lang.String[] {
              "Key", "CheckSum",
            });
    internal_static_grep11_GenerateKeyPairRequest_descriptor =
        getDescriptor().getMessageTypes().get(56);
    internal_static_grep11_GenerateKeyPairRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateKeyPairRequest_descriptor,
            new java.lang.String[] {
              "Mech", "PubKeyTemplate", "PrivKeyTemplate", "PrivKeyId", "PubKeyId",
            });
    internal_static_grep11_GenerateKeyPairRequest_PubKeyTemplateEntry_descriptor =
        internal_static_grep11_GenerateKeyPairRequest_descriptor.getNestedTypes().get(0);
    internal_static_grep11_GenerateKeyPairRequest_PubKeyTemplateEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateKeyPairRequest_PubKeyTemplateEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_grep11_GenerateKeyPairRequest_PrivKeyTemplateEntry_descriptor =
        internal_static_grep11_GenerateKeyPairRequest_descriptor.getNestedTypes().get(1);
    internal_static_grep11_GenerateKeyPairRequest_PrivKeyTemplateEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateKeyPairRequest_PrivKeyTemplateEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_grep11_GenerateKeyPairResponse_descriptor =
        getDescriptor().getMessageTypes().get(57);
    internal_static_grep11_GenerateKeyPairResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GenerateKeyPairResponse_descriptor,
            new java.lang.String[] {
              "PrivKey", "PubKey",
            });
    internal_static_grep11_WrapKeyRequest_descriptor = getDescriptor().getMessageTypes().get(58);
    internal_static_grep11_WrapKeyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_WrapKeyRequest_descriptor,
            new java.lang.String[] {
              "Key", "KeK", "MacKey", "Mech",
            });
    internal_static_grep11_WrapKeyResponse_descriptor = getDescriptor().getMessageTypes().get(59);
    internal_static_grep11_WrapKeyResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_WrapKeyResponse_descriptor,
            new java.lang.String[] {
              "Wrapped",
            });
    internal_static_grep11_UnwrapKeyRequest_descriptor = getDescriptor().getMessageTypes().get(60);
    internal_static_grep11_UnwrapKeyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_UnwrapKeyRequest_descriptor,
            new java.lang.String[] {
              "Wrapped", "KeK", "MacKey", "Mech", "Template", "UnwrappedId",
            });
    internal_static_grep11_UnwrapKeyRequest_TemplateEntry_descriptor =
        internal_static_grep11_UnwrapKeyRequest_descriptor.getNestedTypes().get(0);
    internal_static_grep11_UnwrapKeyRequest_TemplateEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_UnwrapKeyRequest_TemplateEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_grep11_UnwrapKeyResponse_descriptor = getDescriptor().getMessageTypes().get(61);
    internal_static_grep11_UnwrapKeyResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_UnwrapKeyResponse_descriptor,
            new java.lang.String[] {
              "Unwrapped", "CheckSum",
            });
    internal_static_grep11_DeriveKeyRequest_descriptor = getDescriptor().getMessageTypes().get(62);
    internal_static_grep11_DeriveKeyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DeriveKeyRequest_descriptor,
            new java.lang.String[] {
              "Mech", "Template", "BaseKey", "Data", "NewKeyId",
            });
    internal_static_grep11_DeriveKeyRequest_TemplateEntry_descriptor =
        internal_static_grep11_DeriveKeyRequest_descriptor.getNestedTypes().get(0);
    internal_static_grep11_DeriveKeyRequest_TemplateEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DeriveKeyRequest_TemplateEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_grep11_DeriveKeyResponse_descriptor = getDescriptor().getMessageTypes().get(63);
    internal_static_grep11_DeriveKeyResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_DeriveKeyResponse_descriptor,
            new java.lang.String[] {
              "NewKey", "CheckSum",
            });
    internal_static_grep11_GetMechanismListRequest_descriptor =
        getDescriptor().getMessageTypes().get(64);
    internal_static_grep11_GetMechanismListRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GetMechanismListRequest_descriptor, new java.lang.String[] {});
    internal_static_grep11_GetMechanismListResponse_descriptor =
        getDescriptor().getMessageTypes().get(65);
    internal_static_grep11_GetMechanismListResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GetMechanismListResponse_descriptor,
            new java.lang.String[] {
              "Mechs",
            });
    internal_static_grep11_GetMechanismInfoRequest_descriptor =
        getDescriptor().getMessageTypes().get(66);
    internal_static_grep11_GetMechanismInfoRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GetMechanismInfoRequest_descriptor,
            new java.lang.String[] {
              "Mech",
            });
    internal_static_grep11_GetMechanismInfoResponse_descriptor =
        getDescriptor().getMessageTypes().get(67);
    internal_static_grep11_GetMechanismInfoResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GetMechanismInfoResponse_descriptor,
            new java.lang.String[] {
              "MechInfo",
            });
    internal_static_grep11_GetAttributeValueRequest_descriptor =
        getDescriptor().getMessageTypes().get(68);
    internal_static_grep11_GetAttributeValueRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GetAttributeValueRequest_descriptor,
            new java.lang.String[] {
              "Object", "Attributes",
            });
    internal_static_grep11_GetAttributeValueRequest_AttributesEntry_descriptor =
        internal_static_grep11_GetAttributeValueRequest_descriptor.getNestedTypes().get(0);
    internal_static_grep11_GetAttributeValueRequest_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GetAttributeValueRequest_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_grep11_GetAttributeValueResponse_descriptor =
        getDescriptor().getMessageTypes().get(69);
    internal_static_grep11_GetAttributeValueResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GetAttributeValueResponse_descriptor,
            new java.lang.String[] {
              "Attributes",
            });
    internal_static_grep11_GetAttributeValueResponse_AttributesEntry_descriptor =
        internal_static_grep11_GetAttributeValueResponse_descriptor.getNestedTypes().get(0);
    internal_static_grep11_GetAttributeValueResponse_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_GetAttributeValueResponse_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_grep11_SetAttributeValueRequest_descriptor =
        getDescriptor().getMessageTypes().get(70);
    internal_static_grep11_SetAttributeValueRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SetAttributeValueRequest_descriptor,
            new java.lang.String[] {
              "Object", "Attributes",
            });
    internal_static_grep11_SetAttributeValueRequest_AttributesEntry_descriptor =
        internal_static_grep11_SetAttributeValueRequest_descriptor.getNestedTypes().get(0);
    internal_static_grep11_SetAttributeValueRequest_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SetAttributeValueRequest_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_grep11_SetAttributeValueResponse_descriptor =
        getDescriptor().getMessageTypes().get(71);
    internal_static_grep11_SetAttributeValueResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_SetAttributeValueResponse_descriptor,
            new java.lang.String[] {
              "Object",
            });
    internal_static_grep11_Mechanism_descriptor = getDescriptor().getMessageTypes().get(72);
    internal_static_grep11_Mechanism_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_Mechanism_descriptor,
            new java.lang.String[] {
              "Mechanism", "Parameter",
            });
    internal_static_grep11_MechanismInfo_descriptor = getDescriptor().getMessageTypes().get(73);
    internal_static_grep11_MechanismInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_MechanismInfo_descriptor,
            new java.lang.String[] {
              "MinKeySize", "MaxKeySize", "Flags",
            });
    internal_static_grep11_Grep11Error_descriptor = getDescriptor().getMessageTypes().get(74);
    internal_static_grep11_Grep11Error_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grep11_Grep11Error_descriptor,
            new java.lang.String[] {
              "Code", "Detail", "Retry",
            });
  }

  private Hsm() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  // @@protoc_insertion_point(outer_class_scope)
}
