// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

/** Protobuf type {@code grep11.MechanismInfo} */
public final class MechanismInfo extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:grep11.MechanismInfo)
    MechanismInfoOrBuilder {
  public static final int MINKEYSIZE_FIELD_NUMBER = 1;
  public static final int MAXKEYSIZE_FIELD_NUMBER = 2;
  public static final int FLAGS_FIELD_NUMBER = 3;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:grep11.MechanismInfo)
  private static final com.ibm.crypto.grep11.grpc.MechanismInfo DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<MechanismInfo> PARSER =
      new com.google.protobuf.AbstractParser<MechanismInfo>() {
        @java.lang.Override
        public MechanismInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MechanismInfo(input, extensionRegistry);
        }
      };

  static {
    DEFAULT_INSTANCE = new com.ibm.crypto.grep11.grpc.MechanismInfo();
  }

  private long minKeySize_;
  private long maxKeySize_;
  private long flags_;
  private byte memoizedIsInitialized = -1;

  // Use MechanismInfo.newBuilder() to construct.
  private MechanismInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MechanismInfo() {}
  private MechanismInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8:
            {
              minKeySize_ = input.readUInt64();
              break;
            }
          case 16:
            {
              maxKeySize_ = input.readUInt64();
              break;
            }
          case 24:
            {
              flags_ = input.readUInt64();
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.ibm.crypto.grep11.grpc.Hsm.internal_static_grep11_MechanismInfo_descriptor;
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.ibm.crypto.grep11.grpc.MechanismInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static com.ibm.crypto.grep11.grpc.MechanismInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<MechanismInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new MechanismInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ibm.crypto.grep11.grpc.Hsm.internal_static_grep11_MechanismInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ibm.crypto.grep11.grpc.MechanismInfo.class,
            com.ibm.crypto.grep11.grpc.MechanismInfo.Builder.class);
  }

  /**
   * <code>uint64 MinKeySize = 1;</code>
   *
   * @return The minKeySize.
   */
  @java.lang.Override
  public long getMinKeySize() {
    return minKeySize_;
  }

  /**
   * <code>uint64 MaxKeySize = 2;</code>
   *
   * @return The maxKeySize.
   */
  @java.lang.Override
  public long getMaxKeySize() {
    return maxKeySize_;
  }

  /**
   * <code>uint64 Flags = 3;</code>
   *
   * @return The flags.
   */
  @java.lang.Override
  public long getFlags() {
    return flags_;
  }

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (minKeySize_ != 0L) {
      output.writeUInt64(1, minKeySize_);
    }
    if (maxKeySize_ != 0L) {
      output.writeUInt64(2, maxKeySize_);
    }
    if (flags_ != 0L) {
      output.writeUInt64(3, flags_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (minKeySize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeUInt64Size(1, minKeySize_);
    }
    if (maxKeySize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeUInt64Size(2, maxKeySize_);
    }
    if (flags_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeUInt64Size(3, flags_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.ibm.crypto.grep11.grpc.MechanismInfo)) {
      return super.equals(obj);
    }
    com.ibm.crypto.grep11.grpc.MechanismInfo other = (com.ibm.crypto.grep11.grpc.MechanismInfo) obj;

    if (getMinKeySize() != other.getMinKeySize()) return false;
    if (getMaxKeySize() != other.getMaxKeySize()) return false;
    if (getFlags() != other.getFlags()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MINKEYSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getMinKeySize());
    hash = (37 * hash) + MAXKEYSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getMaxKeySize());
    hash = (37 * hash) + FLAGS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getFlags());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MechanismInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ibm.crypto.grep11.grpc.MechanismInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /** Protobuf type {@code grep11.MechanismInfo} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:grep11.MechanismInfo)
      com.ibm.crypto.grep11.grpc.MechanismInfoOrBuilder {
    private long minKeySize_;
    private long maxKeySize_;
    private long flags_;

    // Construct using com.ibm.crypto.grep11.grpc.MechanismInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.ibm.crypto.grep11.grpc.Hsm.internal_static_grep11_MechanismInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ibm.crypto.grep11.grpc.Hsm.internal_static_grep11_MechanismInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ibm.crypto.grep11.grpc.MechanismInfo.class,
              com.ibm.crypto.grep11.grpc.MechanismInfo.Builder.class);
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      minKeySize_ = 0L;

      maxKeySize_ = 0L;

      flags_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.ibm.crypto.grep11.grpc.Hsm.internal_static_grep11_MechanismInfo_descriptor;
    }

    @java.lang.Override
    public com.ibm.crypto.grep11.grpc.MechanismInfo getDefaultInstanceForType() {
      return com.ibm.crypto.grep11.grpc.MechanismInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.ibm.crypto.grep11.grpc.MechanismInfo build() {
      com.ibm.crypto.grep11.grpc.MechanismInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ibm.crypto.grep11.grpc.MechanismInfo buildPartial() {
      com.ibm.crypto.grep11.grpc.MechanismInfo result =
          new com.ibm.crypto.grep11.grpc.MechanismInfo(this);
      result.minKeySize_ = minKeySize_;
      result.maxKeySize_ = maxKeySize_;
      result.flags_ = flags_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ibm.crypto.grep11.grpc.MechanismInfo) {
        return mergeFrom((com.ibm.crypto.grep11.grpc.MechanismInfo) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ibm.crypto.grep11.grpc.MechanismInfo other) {
      if (other == com.ibm.crypto.grep11.grpc.MechanismInfo.getDefaultInstance()) return this;
      if (other.getMinKeySize() != 0L) {
        setMinKeySize(other.getMinKeySize());
      }
      if (other.getMaxKeySize() != 0L) {
        setMaxKeySize(other.getMaxKeySize());
      }
      if (other.getFlags() != 0L) {
        setFlags(other.getFlags());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ibm.crypto.grep11.grpc.MechanismInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ibm.crypto.grep11.grpc.MechanismInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    /**
     * <code>uint64 MinKeySize = 1;</code>
     *
     * @return The minKeySize.
     */
    @java.lang.Override
    public long getMinKeySize() {
      return minKeySize_;
    }

    /**
     * <code>uint64 MinKeySize = 1;</code>
     *
     * @param value The minKeySize to set.
     * @return This builder for chaining.
     */
    public Builder setMinKeySize(long value) {

      minKeySize_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 MinKeySize = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearMinKeySize() {

      minKeySize_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 MaxKeySize = 2;</code>
     *
     * @return The maxKeySize.
     */
    @java.lang.Override
    public long getMaxKeySize() {
      return maxKeySize_;
    }

    /**
     * <code>uint64 MaxKeySize = 2;</code>
     *
     * @param value The maxKeySize to set.
     * @return This builder for chaining.
     */
    public Builder setMaxKeySize(long value) {

      maxKeySize_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 MaxKeySize = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearMaxKeySize() {

      maxKeySize_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>uint64 Flags = 3;</code>
     *
     * @return The flags.
     */
    @java.lang.Override
    public long getFlags() {
      return flags_;
    }
    /**
     * <code>uint64 Flags = 3;</code>
     *
     * @param value The flags to set.
     * @return This builder for chaining.
     */
    public Builder setFlags(long value) {

      flags_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 Flags = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFlags() {

      flags_ = 0L;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:grep11.MechanismInfo)
  }
}
