// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface SetAttributeValueResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.SetAttributeValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Object = 1;</code>
   *
   * @return The object.
   */
  com.google.protobuf.ByteString getObject();
}
