// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface SignFinalResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.SignFinalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Signature = 2;</code>
   *
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
