// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface SignResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.SignResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Signature = 3;</code>
   *
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
