// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface VerifySingleRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.VerifySingleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes PubKey = 1;</code>
   *
   * @return The pubKey.
   */
  com.google.protobuf.ByteString getPubKey();

  /**
   * <code>.grep11.Mechanism Mech = 2;</code>
   *
   * @return Whether the mech field is set.
   */
  boolean hasMech();
  /**
   * <code>.grep11.Mechanism Mech = 2;</code>
   *
   * @return The mech.
   */
  com.ibm.crypto.grep11.grpc.Mechanism getMech();
  /** <code>.grep11.Mechanism Mech = 2;</code> */
  com.ibm.crypto.grep11.grpc.MechanismOrBuilder getMechOrBuilder();

  /**
   * <code>bytes Data = 3;</code>
   *
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>bytes Signature = 4;</code>
   *
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
