// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface VerifyRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.VerifyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes State = 1;</code>
   *
   * @return The state.
   */
  com.google.protobuf.ByteString getState();

  /**
   * <code>bytes Data = 2;</code>
   *
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>bytes Signature = 3;</code>
   *
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
