// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface VerifySingleResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.VerifySingleResponse)
    com.google.protobuf.MessageOrBuilder {}
