// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hsm.proto

package com.ibm.crypto.grep11.grpc;

public interface WrapKeyResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:grep11.WrapKeyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Wrapped = 5;</code>
   *
   * @return The wrapped.
   */
  com.google.protobuf.ByteString getWrapped();
}
